# Generated by Django 6.0.7 on 2026-07-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200, verbose_name='الاسم التجاري')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='الاسم العلمي')),
                ('category', models.CharField(choices=[('tablet', '💊 حبوب / كبسول'), ('syrup', '🧪 شراب'), ('injection', '💉 حقن / فيال'), ('ointment', '🧴 مرهم / كريم'), ('other', '📦 أخرى')], default='tablet', max_length=20, verbose_name='نوع الدواء')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('buy_price', models.IntegerField(verbose_name='سعر الشراء (د.ع)')),
                ('sell_price', models.IntegerField(verbose_name='سعر البيع (د.ع)')),
                ('expiry_date', models.DateField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('shelf_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='مكان الرف')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(verbose_name='الكمية المباعة')),
                ('total_price', models.IntegerField(verbose_name='إجمالي سعر البيع')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت عملية البيع')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='الدواء المباع')),
            ],
        ),
    ]
