# Generated by Django 6.0.7 on 2026-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
