# Generated by Django 6.0.7 on 2026-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_missingmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_damaged',
            field=models.BooleanField(default=False, verbose_name='هل الدواء تالف/معزول؟'),
        ),
    ]
