# Generated by Django 6.0.7 on 2026-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_sale_is_damaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_damaged',
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_damaged',
            field=models.BooleanField(default=False, verbose_name='هل الدواء تالف/معزول؟'),
        ),
    ]
