# Generated by Django 6.0.7 on 2026-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('tablet', '💊 حبوب / كبسول'), ('syrup', '🧪 شراب / معلق'), ('injection', '💉 حقن / فيال / أمبول'), ('ointment', '🧴 مرهم / كريم / جيل'), ('drops_eye_ear', '👁️ قطرات عين / أذن'), ('drops_nasal', '👃 قطرات / بخاخ أنف'), ('suppository', '🍑 تحاميل / لبوس'), ('supplement_vitamin', '🍏 فيتامينات / مكملات غذائية'), ('tonic_energy', '⚡ مقويات / منشطات'), ('powder_sachet', '🥛 بودرة / فوار'), ('medical_device', '🩺 مستلزمات طبية / أجهزة'), ('other', '📦 أخرى')], default='tablet', max_length=20, verbose_name='نوع الدواء'),
        ),
    ]
