# Generated by Django 6.0.7 on 2026-07-15 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_medicine_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصيدلية')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('tablet', '💊 حبوب / كبسول'), ('syrup', '🧪 شراب / معلق'), ('injection', '💉 حقن / فيال / أمبول'), ('ointment', '🧴 مرهم / كريم / جيل'), ('drops_eye_ear', '👁️ قطرات عين / أذن'), ('drops_nasal', '👃 قطرات / بخاخ أنف'), ('suppository', ' تحاميل / لبوس'), ('supplement_vitamin', '🍏 فيتامينات / مكملات غذائية'), ('tonic_energy', '⚡ مقويات / منشطات'), ('powder_sachet', '🥛 بودرة / فوار'), ('medical_device', '🩺 مستلزمات طبية / أجهزة'), ('other', '📦 أخرى')], default='tablet', max_length=20, verbose_name='نوع الدواء'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pharmacy.pharmacybranch'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.pharmacybranch', verbose_name='الصيدلية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingmedicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_medicines', to='pharmacy.pharmacybranch'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pharmacy_owner', models.BooleanField(default=False, verbose_name='هل هو صاحب الصيدلية؟')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pharmacy.pharmacybranch', verbose_name='الصيدلية التابع لها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
