# Generated by Django 6.0.7 on 2026-07-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacybranch_alter_medicine_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_damaged', models.IntegerField(verbose_name='الكمية التالفة')),
                ('reason', models.CharField(choices=[('heat', '🌡️ تلف بسبب الحرارة / انقطاع الكهرباء'), ('storage', '📦 تلف بسبب سوء التخزين / الرطوبة'), ('physical', '💥 كسر / تلف فيزيائي للمنتج'), ('other', '🌀 أسباب أخرى')], default='heat', max_length=20, verbose_name='سبب التلف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('damaged_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الإتلاف')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_records', to='pharmacy.medicine', verbose_name='الدواء')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_medicines', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
            ],
        ),
    ]
