# Generated by Django 6.0.7 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_damagedmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الخصم المالي'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الصافي المدفوع فعلياً'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المجموع قبل الخصم'),
        ),
    ]
