# Generated by Django 6.0.7 on 2026-07-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_invoice_cashier_sale_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='باركود الدواء'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pharmacy.pharmacybranch', verbose_name='الصيدلية'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('pharmacy', 'barcode')},
        ),
    ]
