# Generated by Django 6.0.7 on 2026-07-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_medicine_barcode_sale_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingmedicine',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine', verbose_name='الدواء المرتبط بالمخزن'),
        ),
        migrations.AlterField(
            model_name='missingmedicine',
            name='medicine_name',
            field=models.CharField(max_length=200, verbose_name='اسم الدواء الناقص'),
        ),
        migrations.AlterField(
            model_name='missingmedicine',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الصيدلي'),
        ),
        migrations.CreateModel(
            name='PharmacySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المذخر / المكتب')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
            ],
            options={
                'unique_together': {('pharmacy', 'name')},
            },
        ),
        migrations.AddField(
            model_name='missingmedicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacysupplier', verbose_name='المذخر الموجه له الطلب'),
        ),
    ]
