# Generated by Django 6.0.7 on 2026-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_missingmedicine_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('pharmacy', 'invoice_number')},
        ),
    ]
