# Generated by Django 6.0.7 on 2026-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedmedicine',
            name='quantity_damaged',
            field=models.IntegerField(default=1, verbose_name='الكمية التالفة'),
        ),
        migrations.AlterField(
            model_name='damagedmedicine',
            name='reason',
            field=models.CharField(choices=[('expired', '📆 منتهي الصلاحية'), ('broken', '💔 كسر وضرر'), ('spoiled', '☀️ سوء خزن'), ('withdrawn', '🚫 سحب وزاري'), ('other', '📦 أسباب أخرى')], default='expired', max_length=20, verbose_name='سبب التلف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.IntegerField(default=0, verbose_name='سعر الشراء (د.ع)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='سعر البيع (د.ع)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=1, verbose_name='الكمية المباعة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='إجمالي سعر البيع'),
        ),
    ]
