# Generated by Django 6.0.7 on 2026-07-29 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_damagedmedicine_quantity_damaged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '➕ إنشاء / إضافة'), ('update', '✏️ تعديل'), ('delete', '🗑️ حذف'), ('login', '🔑 تسجيل دخول'), ('logout', '🚪 تسجيل خروج'), ('export', '📥 تصدير بيانات')], max_length=20, verbose_name='نوع الحركة')),
                ('model_name', models.CharField(max_length=100, verbose_name='القسم / الموديل')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العنصر')),
                ('description', models.TextField(verbose_name='تفاصيل الحركة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان ה-IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الحركة')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', '🆓 مجاني (تجريبي)'), ('silver', '🥈 الفضية'), ('gold', '🥇 الذهبية'), ('enterprise', '💎 ماسية / خاصة')], default='free', max_length=20, verbose_name='نوع الخطة')),
                ('status', models.CharField(choices=[('active', '✅ فعال'), ('expired', '❌ منتهي'), ('trial', '⏳ فترة تجريبية'), ('cancelled', '🚫 ملغى')], default='trial', max_length=20, verbose_name='حالة الاشتراك')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الاشتراك')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ انتهاء الاشتراك')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('currency', models.CharField(default='IQD', max_length=10, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('zain_cash', '📱 زين كاش'), ('qi_card', '💳 كي كارت / ماستر كارد'), ('fastpay', '⚡ فاست باي'), ('cash', '💵 نقداً للمندوب'), ('other', '🏦 تحويل بانكي / آخر')], default='zain_cash', max_length=20, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية / التوثيق')),
                ('status', models.CharField(choices=[('success', '✅ ناجح'), ('pending', '⏳ قيد الانتظار'), ('failed', '❌ فاشل')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت السداد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التسديد')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pharmacy.subscription', verbose_name='الاشتراك المرتبط')),
            ],
        ),
    ]
