# Generated by Django 6.0.7 on 2026-08-01 13:55

import django.db.models.deletion
import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_auditlog_subscription_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=pharmacy.models.generate_desktop_license_code, editable=False, max_length=80, unique=True, verbose_name='رمز التفعيل')),
                ('license_type', models.CharField(choices=[('trial', 'تجريبي'), ('annual', 'سنوي'), ('lifetime', 'مدى الحياة')], default='lifetime', max_length=20, verbose_name='نوع الترخيص')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'موقوف'), ('revoked', 'ملغى')], default='active', max_length=20, verbose_name='حالة الترخيص')),
                ('max_devices', models.PositiveSmallIntegerField(default=1, verbose_name='عدد الأجهزة المسموح بها')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الترخيص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_license', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=128, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=120, verbose_name='اسم الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفعيل')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='آخر اتصال')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='pharmacy.desktoplicense', verbose_name='الترخيص')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('license', 'device_fingerprint'), name='unique_device_per_desktop_license')],
            },
        ),
    ]
