# Generated by Django 6.0.7 on 2026-08-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_supplierinvoice_supplierpayment_supplierreturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('refund_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pharmacy.supplierinvoice')),
            ],
            options={
                'ordering': ['refund_date', 'id'],
            },
        ),
    ]
