# Generated by Django 6.0.7 on 2026-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_supplierrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedmedicine',
            name='reason',
            field=models.CharField(choices=[('expired', '📆 منتهي الصلاحية'), ('broken', '💔 كسر وضرر'), ('spoiled', '☀️ سوء خزن'), ('withdrawn', '🚫 سحب وزاري'), ('quantity_correction', '✏️ تعديل كمية (إضافة خاطئة)'), ('other', '📦 أسباب أخرى')], default='expired', max_length=20, verbose_name='سبب التلف'),
        ),
    ]
