# Generated by Django 6.0.7 on 2026-08-14 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_alter_damagedmedicine_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacysupplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='damagedmedicine',
            name='quantity_damaged',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية التالفة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الخصم المالي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الصافي المدفوع فعلياً'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المجموع قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الشراء (د.ع)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المتوفرة'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر البيع (د.ع)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المباعة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي سعر البيع'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='original_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplierrefund',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplierreturn',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
