# Generated by Django 6.0.7 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_alter_pharmacysupplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybranch',
            name='invoice_sequence',
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                verbose_name='آخر رقم فاتورة صادر',
            ),
        ),
    ]
