# Generated by Django 6.0.7 on 2026-08-15

import django.core.validators
from django.db import migrations, models


def copy_current_cost_to_existing_damaged_medicines(apps, schema_editor):
    DamagedMedicine = apps.get_model('pharmacy', 'DamagedMedicine')

    for damaged_medicine in DamagedMedicine.objects.select_related('medicine').iterator():
        damaged_medicine.unit_cost = damaged_medicine.medicine.buy_price or 0
        damaged_medicine.save(update_fields=['unit_cost'])


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_pharmacybranch_invoice_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedmedicine',
            name='unit_cost',
            field=models.IntegerField(
                default=0,
                editable=False,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='سعر شراء الوحدة وقت الإتلاف',
            ),
        ),
        migrations.RunPython(
            copy_current_cost_to_existing_damaged_medicines,
            migrations.RunPython.noop,
        ),
    ]
