# Generated by Django 6.0.7 on 2026-08-15

from django.db import migrations, models


def sync_supplier_invoice_statuses(apps, schema_editor):
    SupplierInvoice = apps.get_model('pharmacy', 'SupplierInvoice')

    for invoice in SupplierInvoice.objects.all().iterator():
        total_paid = invoice.payments.aggregate(total=models.Sum('amount'))['total'] or 0
        total_returned = invoice.returns.aggregate(total=models.Sum('amount'))['total'] or 0
        total_refunded = invoice.refunds.aggregate(total=models.Sum('amount'))['total'] or 0
        remaining_amount = invoice.original_amount - total_returned - total_paid + total_refunded
        new_status = 'paid' if remaining_amount == 0 else 'partial'

        if invoice.status != new_status:
            invoice.status = new_status
            invoice.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_damagedmedicine_unit_cost'),
    ]

    operations = [
        migrations.RunPython(
            sync_supplier_invoice_statuses,
            migrations.RunPython.noop,
        ),
    ]
