# Generated by Django 6.0.7 on 2026-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_sync_supplier_invoice_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('download_url', models.URLField()),
                ('release_notes', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
