# Generated by Django 6.0.7 on 2026-09-16

from django.db import migrations, models
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_desktopappversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('rent', 'إيجار'), ('salaries', 'رواتب'), ('utilities', 'كهرباء وماء وإنترنت'), ('maintenance', 'صيانة'), ('transport', 'نقل ومواصلات'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ المصروف')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('pharmacy', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='expenses', to='pharmacy.pharmacybranch', verbose_name='الصيدلية')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['pharmacy', 'expense_date'], name='pharmacy_ex_pharmac_97cfe0_idx'), models.Index(fields=['pharmacy', 'expense_type'], name='pharmacy_ex_pharmac_679ebc_idx')],
            },
        ),
    ]
