# Generated by Django 6.0.7 on 2026-09-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_expense'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='pharmacy_ex_pharmac_f86b8e_idx',
            old_name='pharmacy_ex_pharmac_97cfe0_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='pharmacy_ex_pharmac_4c5876_idx',
            old_name='pharmacy_ex_pharmac_679ebc_idx',
        ),
    ]
