# Generated by Django 6.0.7 on 2026-09-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0027_rename_pharmacy_ex_pharmac_97cfe0_idx_pharmacy_ex_pharmac_f86b8e_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesktopAppVersion',
        ),
        migrations.RemoveField(
            model_name='desktoplicense',
            name='pharmacy',
        ),
        migrations.RemoveConstraint(
            model_name='deviceactivation',
            name='unique_device_per_desktop_license',
        ),
        migrations.RemoveField(
            model_name='deviceactivation',
            name='license',
        ),
        migrations.DeleteModel(
            name='DesktopLicense',
        ),
        migrations.DeleteModel(
            name='DeviceActivation',
        ),
    ]
